apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stroom-proxy.fullname" . }}
  labels:
    {{- include "stroom-proxy.labels" . | nindent 4 }}
data:
  config.yml: |
    server:
      applicationContextPath: /
      adminContextPath: /proxyAdmin
      applicationConnectors:
        - type: http
          port: {{ .Values.ports.app }}
      adminConnectors:
        - type: http
          port: {{ .Values.ports.admin }}
      requestLog:
        {{- with .Values.logging }}
        appenders:
          - type: file
            currentLogFilename: {{ printf "%s/access/access.log" .baseDir }}
            threshold: ALL
            queueSize: 256
            discardingThreshold: 0
            archive: {{ .archive.enabled }}
            archivedLogFilenamePattern: {{ printf "%s/access/access-%%d{%s}.log.gz" .baseDir .fileDateFormat }}
            archivedFileCount: {{ .archive.maxFileCount }}
            timeZone: {{ .timeZone }}
            logFormat: '%h %l "%u" [%t] "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D'
        {{- end }}

    logging:
      {{- with .Values.logging }}
      level: {{ .level }}
      loggers:
        stroom: INFO
        io.dropwizard: INFO
        org.eclipse.jetty: INFO
        org.flywaydb: INFO
        "receive":
          level: INFO
          additive: false
          appenders:
            - type: file
              currentLogFilename: {{ printf "%s/receive/receive.log" .baseDir }}
              threshold: ALL
              queueSize: 256
              discardingThreshold: 0
              archive: {{ .archive.enabled }}
              archivedLogFilenamePattern: {{ printf "%s/receive/receive-%%d{%s}.log.gz" .baseDir .fileDateFormat }}
              archivedFileCount: {{ .archive.maxFileCount }}
              timeZone: {{ .timeZone }}
              logFormat: "%-6level [%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}] [%t] %logger - %X{code} %msg %n"
        "send":
          level: INFO
          additive: false
          appenders:
            - type: file
              currentLogFilename: {{ printf "%s/send/send.log" .baseDir }}
              threshold: ALL
              queueSize: 256
              discardingThreshold: 0
              archive: {{ .archive.enabled }}
              archivedLogFilenamePattern: {{ printf "%s/send/send-%%d{%s}.log.gz" .baseDir .fileDateFormat }}
              archivedFileCount: {{ .archive.maxFileCount }}
              timeZone: {{ .timeZone }}
              logFormat: "%-6level [%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}] [%t] %logger - %X{code} %msg %n"
      {{- end }}

      appenders:
        {{- with .Values.logging }}
        - type: console
          logFormat: "%highlight(%-6level) [%d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC}] [%green(%t)] %cyan(%logger) - %X{code} %msg %n"
          timeZone: {{ .timeZone }}
        - type: file
          currentLogFilename: {{ printf "%s/app/app.log" .baseDir }}
          threshold: ALL
          queueSize: 256
          discardingThreshold: 0
          archive: {{ .archive.enabled }}
          archivedLogFilenamePattern: {{ printf "%s/app/app-%%d{%s}.log.gz" .baseDir .fileDateFormat }}
          archivedFileCount: {{ .archive.maxFileCount }}
          timeZone: {{ .timeZone }}
          logFormat: "%-6level [%d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC}] [%t] %logger - %X{code} %msg %n"
        {{- end }}

    proxyConfig:
      aggregator:
        {{- with .Values.repository.aggregation }}
        enabled: {{ .enabled }}
        aggregationFrequency: {{ .frequency | quote }}
        maxAggregateAge: {{ .maxAge | quote }}
        maxItemsPerAggregate: {{ .maxItems }}
        maxUncompressedByteSize: {{ .maxUncompressedSizeBytes | quote }}
        {{- end }}

      feedStatus:
        url: {{ include "stroom-proxy.feedStatusUrl" . | quote }}
        apiKey: "${FEED_STATUS_API_KEY}"

      {{- if .Values.forwarding.enabled }}
      forwardDestinations:
        - type: post
          name: stroom
          forwardUrl: {{ include "stroom-proxy.forwardUrl" . | quote }}
          enabled: {{ .Values.forwarding.enabled }}
          sslConfig:
            keyStorePath: {{ include "stroom-proxy.keyStorePath" . }}
            keyStorePassword: "${KEYSTORE_PASSWORD}"
            keyStoreType: {{ .Values.keyStore.type }}
            trustStorePath: {{ include "stroom-proxy.trustStorePath" . }}
            trustStorePassword: "${TRUSTSTORE_PASSWORD}"
            trustStoreType: {{ .Values.trustStore.type }}
            hostnameVerificationEnabled: {{ .Values.forwarding.tls.verifyHostName }}
      {{- end }}

      path:
        home: "/stroom-proxy/"
        temp: "/tmp/stroom-proxy"

      logStream:
        metaKeys: "guid,feed,system,environment,remotehost,remoteaddress,remotedn,remotecertexpiry"

      db:
        dbDir: db

      repository:
        {{- with .Values.repository }}
        repoDir: repo
        storingEnabled: {{ .storing.enabled }}
        {{- end }}

      # restClient is used for making feed status REST calls
      restClient:
        {{- with .Values.restClient }}
        chunkedEncodingEnabled: true
        connectionTimeout: {{ .connectionTimeout | quote }}
        {{- end }}
        tls:
          keyStorePath: {{ include "stroom-proxy.keyStorePath" . }}
          keyStorePassword: "${KEYSTORE_PASSWORD}"
          keyStoreType: {{ .Values.keyStore.type }}
          trustStorePath: {{ include "stroom-proxy.trustStorePath" . }}
          trustStorePassword: "${TRUSTSTORE_PASSWORD}"
          trustStoreType: {{ .Values.trustStore.type }}
          verifyHostname: {{ .Values.stroom.tls.verifyHostName }}
          trustSelfSignedCertificates: {{ .Values.stroom.tls.trustSelfSignedCertificates }}

      {{- with .Values.threads }}
      threads:
        examineSourceThreadCount: {{ .examineSource }}
        forwardRetryThreadCount: {{ .forwardRetry }}
        forwardThreadCount: {{ .forwardRetry }}
      {{- end }}

      useDefaultOpenIdCredentials: false