apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stroom-proxy.fullname" . }}
  labels:
    {{- include "stroom-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "stroom-proxy.fullname" . }}
  selector:
    matchLabels:
      {{- include "stroom-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stroom-proxy.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.keyStore.passwordSecretRef | nindent 18 }}
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.trustStore.passwordSecretRef | nindent 18 }}
            - name: FEED_STATUS_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.stroom.apiKeySecretRef | nindent 18 }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.forwarding.enabled }}
            - mountPath: {{ include "stroom-proxy.keyStorePath" . }}
              subPath: {{ .Values.keyStore.secretRef.key }}
              name: keystore
              readOnly: true
            {{- end }}
            {{- if .Values.forwarding.enabled }}
            - mountPath: {{ include "stroom-proxy.trustStorePath" . }}
              subPath: {{ .Values.trustStore.secretRef.key }}
              name: truststore
              readOnly: true
            {{- end }}
            - mountPath: /stroom-proxy/config
              name: config
              readOnly: true
            - mountPath: /stroom-proxy/content
              subPath: content
              name: data
            - mountPath: /stroom-proxy/logs
              subPath: logs
              name: data
            - mountPath: /stroom-proxy/repo
              subPath: repo
              name: data
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $name, $number := .Values.ports }}
            - name: {{ $name }}
              containerPort: {{ $number }}
              protocol: TCP
            {{- end }}
          startupProbe:
            httpGet:
              path: /proxyAdmin/filteredhealthcheck?deny=stroom.proxy.app.handler.RemoteFeedStatusService,stroom.proxy.app.handler.ForwardStreamHandlerFactory
              port: admin
            {{- toYaml .Values.probeTimings.startup | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /proxyAdmin/filteredhealthcheck?deny=stroom.proxy.app.handler.RemoteFeedStatusService,stroom.proxy.app.handler.ForwardStreamHandlerFactory
              port: admin
            {{- toYaml .Values.probeTimings.readiness | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /proxyAdmin/filteredhealthcheck?deny=stroom.proxy.app.handler.RemoteFeedStatusService,stroom.proxy.app.handler.ForwardStreamHandlerFactory
              port: admin
            {{- toYaml .Values.probeTimings.liveness | nindent 12 }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: keystore
          secret:
            secretName: {{ .Values.keyStore.secretRef.name }}
        - name: truststore
          secret:
            secretName: {{ .Values.trustStore.secretRef.name }}
        - name: config
          configMap:
            name: {{ include "stroom-proxy.fullname" . }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.volumeClaims }}
  volumeClaimTemplates:
    {{- range $name, $volumeClaim := . }}
    - metadata:
        name: {{ $name }}
        labels:
          {{- include "stroom-proxy.labels" $ | nindent 10 }}
      spec:
        {{- toYaml $volumeClaim | nindent 8 }}
    {{- end }}
  {{- end }}